name: "CDK Diff v8"

on:
  workflow_call:
    inputs:

      AWS_REGION:
        type: string
        required: true

      CDK_FOLDER_NAME:
        type: string
        required: true

      CDK_PREFIX:
        type: string
        required: true

      ENVIRONMENT_LONG_NAME:
        type: string
        required: true

      NODE_VERSION:
        type: string
        required: false
        default: '20.x'

      YARN_VERSION:
        type: string
        required: false
        default: "4.2.2"
        description: "version of yarn, ex: classic, latest, stable, 4.x.x"

      RUNS_ON:
        type: string
        required: false
        default: ubuntu-latest-8-cores

      TARGET_AWS_ACCOUNT_ROLE_ARN:
        type: string
        required: true

      YARN_DIFF_COMMAND:
        type: string
        required: true

    secrets:
      # required for using github package manager
      NPM_TOKEN:
        required: true

jobs:

  cdk_diff:

    runs-on: ${{ inputs.RUNS_ON }}

    permissions: # github oidc
      id-token: write
      contents: read

    steps:
      - name: echo
        run: |
          echo AWS_REGION ${{ inputs.AWS_REGION }}
          echo CDK_FOLDER_NAME ${{ inputs.CDK_FOLDER_NAME }}
          echo CDK_PREFIX ${{ inputs.CDK_PREFIX }}
          echo ENVIRONMENT_LONG_NAME ${{ inputs.ENVIRONMENT_LONG_NAME }}
          echo NODE_VERSION ${{ inputs.NODE_VERSION }}
          echo RUNS_ON ${{ inputs.RUNS_ON }}
          echo TARGET_AWS_ACCOUNT_ROLE_ARN ${{ inputs.TARGET_AWS_ACCOUNT_ROLE_ARN }}
          echo YARN_VERSION ${{ inputs.YARN_VERSION }}
          echo YARN_DIFF_COMMAND ${{ inputs.YARN_DIFF_COMMAND }}

      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.NPM_TOKEN }} # matches github-torus-packages - repo, packages

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.NODE_VERSION}}
          cache: 'yarn'

      - name: setup yarn and github registry
        run: |
          corepack enable
          yarn set version ${{ inputs.YARN_VERSION }}
          yarn config set npmScopes.torusco.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.torusco.npmAlwaysAuth true
          yarn config set npmScopes.torusco.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: yarn install && yarn build
        run: |
          yarn install
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: CDK_PREFIX
        run: |
          echo "CDK_PREFIX=${{ inputs.CDK_PREFIX }}" >> $GITHUB_ENV

      - name: Deployer Role with Github OIDC Provider
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{inputs.TARGET_AWS_ACCOUNT_ROLE_ARN}}
            aws-region: ${{inputs.AWS_REGION}}

      - name: CDK Diff
        run: |
          ${{ inputs.YARN_DIFF_COMMAND }}
