name: "CDK Tests v2"

on:
  workflow_call:
    inputs:
    
      AWS_REGION:
        type: string
        required: true

      CDK_FOLDER_NAME:
        type: string
        required: true

      SAML_AWS_ROLE_ARN:
        type: string
        required: true

jobs:

  cdk-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: saml-to/assume-aws-role@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          role: ${{ inputs.SAML_AWS_ROLE_ARN }}
          region: ${{ inputs.AWS_REGION }}
          provider: awsProduction

      - name: Yarn Install
        run: |
          # if no .npmrc in repo, fail
          yarn install

      - name: Yarn Build
        run: |
          yarn build

      - name: Yarn Test
        run: |
          ls
          yarn pipeline:test

      - name: CDK Synth
        run: |
          export CDK_PREFIX=pullrequest
          yarn synth

      - name: Install cfn_nag
        run: |
          sudo gem install cfn-nag

      - name: cfn_nag
        run: |
          cfn_nag_scan --input-path ${{ inputs.CDK_FOLDER_NAME }}/cdk.out/*.template.json

