name: "CDK Deploy v2"

on:
  workflow_call:

    inputs:
  
      AWS_REGION:
        type: string
        required: true

      CDK_FOLDER_NAME:
        description: "use this folder with lerna monorepos that contain a cdk- folder, otherwise use YARN_FOLDER_NAME and set this to ."
        type: string
        required: true

      CDK_PREFIX:
        type: string
        required: true

      GITHUB_ENVIRONMENT_GATE:
        description: "a string that matches the GitHub Environment for this repository, acts as a deployment block"
        type: string
        required: true

      SAML_AWS_ROLE_ARN:
        type: string
        required: true

      TARGET_AWS_ACCOUNT_ROLE_ARN:
        type: string
        required: true

      YARN_FOLDER_NAME:
        description: "use this folder repos that contain a series of cdk- folders but no parent and yarn needs to run within the cdk- folder not the root"
        type: string
        required: true
        default: "."

    secrets:

      NPM_TOKEN: 
        description: "provides access to github private repository with Torus shared packages for yarn"
        required: true

jobs:

  cdk-deploy:

    runs-on: ubuntu-latest
    environment: ${{ inputs.GITHUB_ENVIRONMENT_GATE }}
    steps:
      - uses: actions/checkout@v2

      - name: Yarn Install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ${{ inputs.YARN_FOLDER_NAME }}
          yarn install

      - name: Yarn Build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ${{ inputs.YARN_FOLDER_NAME }}
          yarn build

      - name: CDK_PREFIX
        run: |
          echo "CDK_PREFIX=${{ inputs.CDK_PREFIX }}" >> $GITHUB_ENV

      # have to assume this role so can assume deployer role
      - uses: saml-to/assume-aws-role@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          role: ${{ inputs.SAML_AWS_ROLE_ARN }}
          region: ${{ inputs.AWS_REGION }}
          provider: awsProduction

      - name: Deployer Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.TARGET_AWS_ACCOUNT_ROLE_ARN }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-duration-seconds: 3600

      - name: CDK Deploy
        run: |
          cd ${{ inputs.YARN_FOLDER_NAME }}
          yarn pipeline:deploy
