name: "Mobile Jira v6"

on:
  workflow_call:
    inputs:
      MOBILE_STAGE:
        type: string
        required: true

jobs:

  notify_jira:
    runs-on: ubuntu-latest-4-cores
    environment: ${{ inputs.MOBILE_STAGE }}
    steps:
      - run: echo "Reported to Jira in ${{ inputs.MOBILE_STAGE }} deployment"
