name: slack v3

on:
  workflow_call:

    inputs:
  
      SLACK_USERNAME:
        type: string
        required: true
        description: name the message is from
  
    secrets:
  
      SLACK_WEBHOOK:
        required: true

jobs:

  slack_notification:

    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ inputs.SLACK_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}