name: "Terraform Pull Request Checkov Tests v8"

on:
  workflow_call:
    inputs:
      CDK_PREFIX:
        type: string
        required: true

      ENVIRONMENT_LONG_NAME:
        type: string
        required: true
      
      PY_VERSION:
        description: "the python version to install, ex 3.10 or 3.11"
        type: string
        required: false
        default: "3.12"
  
      RUNS_ON:
        type: string
        required: false
        default: ubuntu-latest

      TARGET_TERRAFORM_FOLDER_NAME:
        type: string
        required: true

      TERRAFORM_VERSION:
        type: string
        required: false
        default: "1.7.3"
  
    secrets:
      # required for using github package manager
      NPM_TOKEN:
        required: true

jobs:
  terraform_checkov:

    runs-on: ${{ inputs.RUNS_ON }}

    steps:
      - name: echo
        run: |
          echo CDK_PREFIX ${{ inputs.CDK_PREFIX }}
          echo ENVIRONMENT_LONG_NAME ${{ inputs.ENVIRONMENT_LONG_NAME }}
          echo PY_VERSION ${{ inputs.PY_VERSION }}
          echo RUNS_ON ${{ inputs.RUNS_ON }}
          echo TARGET_TERRAFORM_FOLDER_NAME ${{ inputs.TARGET_TERRAFORM_FOLDER_NAME }}
          echo TERRAFORM_VERSION ${{ inputs.TERRAFORM_VERSION }}
          echo "GITHUB_RUN_URL_FOR_SLACK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV

      - if: github.event.client_payload.ref != ''
        name: GITHUB_CHECKOUT_REF
        run: |
          echo "use ${{ github.event.client_payload.ref }} not ${{ github.ref }}"
          echo "GITHUB_CHECKOUT_REF=${{ github.event.client_payload.ref_name }}" >> $GITHUB_ENV

      - if: github.event.client_payload.ref != ''
        name: actions/checkout@v4 client payload ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

      - if: github.event.client_payload.ref == ''
        name: GITHUB_CHECKOUT_REF
        run: |
          echo "use default ${{ github.ref }}"
          echo "GITHUB_CHECKOUT_REF=${{ github.ref_name }}" >> $GITHUB_ENV

      - if: github.event.client_payload.ref == ''
        name: actions/checkout@v4 default ref
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PY_VERSION }}

      - name: Install checkov
        run: |
          python -c "import sys; print(sys.version)"
          pip install checkov

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: true
          terraform_version: ${{ inputs.TERRAFORM_VERSION }}
  
      - name: Environment Variables
        run: |
          echo "CDK_PREFIX=${{ inputs.CDK_PREFIX }}" >> $GITHUB_ENV
          echo "TF_VAR_CDK_PREFIX=${{ inputs.CDK_PREFIX }}" >> $GITHUB_ENV
          echo "TF_VAR_TORUS_ENVIRONMENT=${{ inputs.ENVIRONMENT_LONG_NAME }}" >> $GITHUB_ENV

      - name: Terraform Checkov
        run: |
          cd ${{ inputs.TARGET_TERRAFORM_FOLDER_NAME }}
          terraform --version
          checkov -d .
