name: "Yarn Pull Request Unit Tests v8"

on:
  workflow_call:
    inputs:
    
      AWS_REGION:
        type: string
        required: true

      RUNS_ON:
        type: string
        required: false
        default: ubuntu-latest

      YARN_TEST_COMMAND:
        type: string
        required: true
      
      USES_SONAR_CLOUD:
        type: boolean
        default: true
        required: false

      USES_SONAR_CLOUD_MAIN_ANALYSIS:
        type: boolean
        default: false
        required: false
        description: "override the branch from the event, and run on main, use with USES_SONAR_CLOUD for sonar cloud main analysis "

    secrets:
      SONAR_TOKEN:
        required: false

      # required for using github package manager
      NPM_TOKEN:
        required: true

jobs:

  cdk_test:

    runs-on: ${{ inputs.RUNS_ON }}

    steps:

      - name: Checkout USES_SONAR_CLOUD and USES_SONAR_CLOUD_MAIN_ANALYSIS
        uses: actions/checkout@v3
        if: "${{ inputs.USES_SONAR_CLOUD == true && inputs.USES_SONAR_CLOUD_MAIN_ANALYSIS == true }}"
        with: 
          fetch-depth: 0     # sonar cloud - Number of commits to fetch. 0 indicates all history for all branches and tags.
          ref: main  # we want to force the ref to main
          token: ${{ secrets.NPM_TOKEN }} # matches github-torus-packages - repo, packages

      - name: Checkout USES_SONAR_CLOUD and not USES_SONAR_CLOUD_MAIN_ANALYSIS
        uses: actions/checkout@v3
        if: "${{ inputs.USES_SONAR_CLOUD == true && inputs.USES_SONAR_CLOUD_MAIN_ANALYSIS == false }}"
        with: 
          fetch-depth: 0     # sonar cloud - Number of commits to fetch. 0 indicates all history for all branches and tags.
          token: ${{ secrets.NPM_TOKEN }} # matches github-torus-packages - repo, packages
          # will take ref from the event (PR branch)

      - name: Checkout not USES_SONAR_CLOUD
        uses: actions/checkout@v3
        if: "${{ inputs.USES_SONAR_CLOUD == false }}"
        # clean regular checkout, no sonar cloud, no refs
        with: 
          token: ${{ secrets.NPM_TOKEN }} # matches github-torus-packages - repo, packages

      - name: use github as yarn registry
        uses: actions/setup-node@v3 # Found that this action uses deprecated set-output command, filed bug with developers: https://github.com/actions/setup-node/issues/606
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'
          always-auth: true
          scope: '@torusco'
          cache: 'yarn'      

      - name: yarn install && yarn build
        run: |
          yarn install
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ${{ inputs.YARN_TEST_COMMAND }}
        run: |
          ${{ inputs.YARN_TEST_COMMAND }}

      # instead of hacking it here, add this to the sonar-project.properties!
      - name: SonarCloud Set Main
        if: "${{ inputs.USES_SONAR_CLOUD == true && inputs.USES_SONAR_CLOUD_MAIN_ANALYSIS == true }}"
        run: |
          echo -e "\nsonar.branch.name=main" >> sonar-project.properties
          cat sonar-project.properties

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: "${{ inputs.USES_SONAR_CLOUD != '' }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



