name: Publish a Package v2

on:
  push:
    branches:
      - main

env:
  ARTIFACT_RETENTION_COUNT: 5

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@torus.co

      - name: use github as yarn registry
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@torusinc'
      
      - run: yarn install && yarn build

      - name: version publish tag
        id: version
        run: |      
          yarn config set version-tag-prefix "v"
          yarn config set version-git-tag true
          yarn version --patch
          yarn publish
          git push
          git push --tags
          NEW_VERSION=`git tag  | grep -E '^v[0-9]' | sort -V | tail -1`
          echo "::set-output name=value::$NEW_VERSION"
          echo $NEW_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release notes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.value }}
          name: ${{ steps.version.outputs.value }}
          generateReleaseNotes: true
        
      - uses: actions/delete-package-versions@v3
        with: 
          package-name: 'cdk-shared'
          min-versions-to-keep: ${{ env.ARTIFACT_RETENTION_COUNT }}

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: ${{ env.ARTIFACT_RETENTION_COUNT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
            
