name: "Yarn Pull Request Tests v4"

# Release Notes v4
#   switches to github package manager

on:
  workflow_call:
    inputs:
    
      AWS_REGION:
        type: string
        required: true

      CDK_FOLDER_NAME:
        type: string
        required: true

      INTEGRATION_TEST_ENVIRONENT:
        type: string
        required: false

      SAML_AWS_ROLE_ARN:
        type: string
        required: true

      TARGET_AWS_ACCOUNT_ROLE_ARN:
        type: string
        required: false
      
      USES_INTEGRATION_TEST:
        type: boolean
        required: false

      USES_SONAR_CLOUD:
        type: boolean
        default: true 
        required: false

      USES_SONAR_CLOUD_MAIN_ANALYSIS:
        type: boolean
        default: false 
        required: false
        description: "override the branch from the event, and run on main, use with USES_SONAR_CLOUD for sonar cloud main analysis "

      USES_CDK_NAG: 
        type: boolean
        default: false 
        required: false

    secrets:
      SONAR_TOKEN:
        required: false

      # required for using github package manager
      NPM_TOKEN:
        required: true

jobs:

  cdk-test:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        if: "${{ inputs.USES_SONAR_CLOUD == 'true' && inputs.USES_SONAR_CLOUD_MAIN_ANALYSIS == 'true'}}"
        with: 
          fetch-depth: 0     # sonar cloud - Number of commits to fetch. 0 indicates all history for all branches and tags.
          ref: main  # we want to force the ref to main

      - uses: actions/checkout@v3
        if: "${{ inputs.USES_SONAR_CLOUD == 'true' && inputs.USES_SONAR_CLOUD_MAIN_ANALYSIS == 'false'}}"
        with: 
          fetch-depth: 0     # sonar cloud - Number of commits to fetch. 0 indicates all history for all branches and tags.
          # will take ref from the event (PR branch)

      - uses: actions/checkout@v3
        if: "${{ inputs.USES_SONAR_CLOUD == 'false' }}"
        # clean regular checkout, no sonar cloud, no refs

      - uses: saml-to/assume-aws-role@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          role: ${{ inputs.SAML_AWS_ROLE_ARN }}
          region: ${{ inputs.AWS_REGION }}
          provider: awsProduction

      - name: Yarn Install
        run: |
          yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Yarn Build
        run: |
          yarn build

      - name: Yarn Unit Test
        run: |
          yarn pipeline:test-unit

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: "${{ inputs.USES_SONAR_CLOUD != '' }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: CDK Synth with CDK Nag
        if: "${{ inputs.USES_CDK_NAG != '' }}"
        run: |
          export CDK_PREFIX=pullrequest
          yarn synth

      - name: Integration Test Role
        if: "${{ inputs.USES_INTEGRATION_TEST != '' }}"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.TARGET_AWS_ACCOUNT_ROLE_ARN }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Yarn Integration Test
        if: "${{ inputs.USES_INTEGRATION_TEST != '' }}"
        run: |
          export CDK_PREFIX=${{ inputs.INTEGRATION_TEST_ENVIRONENT}}
          yarn pipeline:test-int



